### ISSUE TITLE
get_jackknife_sd issue

### ISSUE THREAD

**Issue by DanielRamos12** [simonhmartin/tutorials#2]
Dear Simon;

I'm following your fantastic tutorial. However, when computing the function "get_jackknife_sd", I get the following issue:

![image](https://user-images.githubusercontent.com/64471093/80483706-6f8a2400-894e-11ea-9c25-9c5c6c636b19.png)

I tried to fix it but I couldn't, any idea?

**Comment by simonhmartin** [comment]
Sorry for the long delay - I missed this question.
You shouldn't get this bug If you use the current version of `jackknife.R` from here: https://github.com/simonhmartin/genomics_general
